export const HERO_HEADLINE = "ENGINEERING MODERN INTERFACES";
export const HERO_LEAD_PREFIX =
  "Paul-Valentin Mini builds frontend platforms from concept to full-rate production through";
export const HERO_LEAD_HIGHLIGHT = "react architecture, design systems, and applied AI.";
export const HERO_VIDEO_URL =
  "https://player.vimeo.com/video/1168134399?muted=1&autoplay=1&loop=1&background=1&app_id=122963";

export const SUBHEAD_PARTNER = "Your Partner For Cross-Platform Frontend Engineering";
export const SUBHEAD_BODY =
  "Lead Frontend Engineer with over 10 years of experience designing and scaling web and mobile applications for global platforms like Samsung SmartThings. Expert in React, Next.js, and modern JavaScript ecosystems, with a proven track record of overhauling developer consoles and building robust internal component libraries.";

export const EYEBROW_EXPERIENCE = "FEATURED ROLES";
export const EYEBROW_SKILLS = "TOP SKILLS";
export const EYEBROW_EDU = "EDUCATION & CERTIFICATIONS";
export const EYEBROW_CONTACT = "CONTACT";

export const EXPERIENCES = [
  {
    company: "SmartThings",
    location: "San Francisco, CA",
    role: "Senior Software Developer",
    dates: "January 2020 – Present",
    bullets: [
      "Lead developer for the SmartThings Developer Console, unifying UX across multiple web products while partnering with global teams (Poland, Indonesia, Korea) to integrate cross-functional features.",
      "Actively contributed to the company's AI pilot program as a designated power user. Engineered a template repository providing AI-driven prompts and skills to bootstrap product integrations.",
      "Initiated and led the complete refactoring of the platform's onboarding experience, taking proactive ownership to drive the project from proof-of-concept to a successful production release.",
      "Streamlined platform development by building a React component library that enforced Samsung's One Design guidelines to unify cross-brand UX, managing zero-break global NPM releases, and maintaining a JavaScript SDK autogenerated from OpenAPI specifications.",
    ],
    stack:
      "JavaScript, TypeScript, React, Next.js, Docker, Spinnaker, Kubernetes, Terraform, GitHub Actions, Jenkins, Copilot, Claude, Gemini, Python",
  },
  {
    company: "Samsung Research America",
    location: "San Francisco, CA",
    role: "Software Developer",
    dates: "March 2018 – January 2020",
    bullets: [
      "Transitioned to web frontend development for ARTIK Cloud, instrumental in launching the Developer Workspace (a portal for managing SmartThings integrations).",
      "Developed a modern JavaScript SDK and specialized Starter Kits to improve the 3rd-party developer experience.",
      "Maintained ARTIK Cloud's iOS developer tooling alongside web responsibilities.",
    ],
    stack:
      "JavaScript, TypeScript, React, Next.js, Docker, Spinnaker, Kubernetes, Swift, App Store Connect, TestFlight",
  },
  {
    company: "Samsung Strategy & Innovation Center",
    location: "San Francisco, CA",
    role: "iOS Developer",
    dates: "June 2016 – March 2018",
    bullets: [
      "Hired directly under executive leadership (Luc Julia, co-creator of Siri) to served as the lead iOS developer for ARTIK Cloud.",
      "Conceptualized and engineered the ARTIK Cloud iOS application from the ground up.",
      "Developed and maintained a Universal Framework (SDK) enabling 3rd-party developers to build natively across iOS, tvOS, watchOS, and macOS.",
      "Navigated strict Apple OS limitations (background task restrictions, location tracking) to ensure seamless application performance and reliable data syncing.",
    ],
    stack: "Swift, Objective-C, App Store Connect, TestFlight",
  },
  {
    company: "Prism",
    location: "San Francisco, CA",
    role: "iOS & Backend Developer",
    dates: "October 2015 – May 2016",
    bullets: [
      "Engineered an iOS application and its supporting backend architecture designed for automated, smart image classification.",
      "Pioneered a computer vision–driven photo classification system predating native iOS Visual Search, utilizing OpenCV, Tesseract, and Python to identify apps from screenshots and execute Deep Link Lookups.",
      "Designed a highly performant and scalable REST API backed by a PostgreSQL database with Redis caching.",
    ],
    stack: "Python, Django, PostgreSQL, Redis, SQLite, tesseract-ocr, OpenCV",
  },
  {
    company: "Imprivata",
    location: "Santa Cruz, CA",
    role: "Android Developer (Capstone Partnership)",
    dates: "January 2015 – August 2015",
    bullets: [
      "Developed an end-to-end encrypted Android application to facilitate secure, confidential document sharing between patients and medical professionals in strict accordance with HIPAA regulations.",
      "Architected the data synchronization flow using an internal SQLite database communicating with a Python/MySQL backend.",
    ],
    stack: "Java, Android Studio, MySQL, SQLite, REST, Python",
  },
] as const;

export const EDUCATION = [
  {
    title: "B.A. Computer Science",
    detail: "University of California, Santa Cruz (UCSC)",
  },
  {
    title: "Practical Prompt Engineering",
    detail: "Instructor: Sabrina Goldfarb (GitHub) | Completed Dec 2025",
  },
  {
    title: "AI Agents Fundamentals, v2",
    detail: "Instructor: Scott Moss (Netflix) | In Progress",
  },
] as const;

export const CONTACT = {
  name: "Paul-Valentin Mini",
  location: "San Francisco, CA",
  phone: "(415) 694-3616",
  email: "paul@emini.com",
  linkedin: "https://www.linkedin.com/in/pvmini",
  github: "https://github.com/Laptopmini",
} as const;

export const WORDMARK_TEXT = "PVMINI";

export const AI_FOOTER_EYEBROW = "AI-DEVELOPED RESUME";
export const AI_FOOTER_HEADLINE = "Built with AI";
export const AI_FOOTER_BODY =
  "This resume was built with AI-assisted development using a deterministic bash loop (The Ralph Loop).";
export const AI_FOOTER_WORKFLOW =
  "Each section, component, and deployment artifact was generated through a deterministic bash loop with zero human intervention on the codebase.";
export const AI_FOOTER_REPO_LABEL = "RESUME REPO";
export const AI_FOOTER_REPO_URL = "https://github.com/Laptopmini/resume-rebuildmanufacturing";
export const AI_FOOTER_RALPH_URL = "https://github.com/Laptopmini/ralph-node";

export const SKILLS = [
  {
    category: "Frontend",
    items: ["React", "TypeScript", "Next.js", "JavaScript", "CSS", "HTML"],
  },
  {
    category: "Backend & DevOps",
    items: ["Node.js", "Python", "Docker", "Kubernetes", "Terraform", "Jenkins"],
  },
  {
    category: "Mobile & Frameworks",
    items: ["iOS", "Swift", "Android", "React Native", "Expo"],
  },
  {
    category: "AI & Tools",
    items: ["OpenAI", "Claude", "Gemini", "GitHub Copilot", "CI/CD"],
  },
] as const;

export const STATS = [
  { label: "Years Experience", value: "10", suffix: "+" },
  { label: "Production Apps", value: "8", suffix: "+" },
  { label: "NPM Releases", value: "50", suffix: "+" },
  { label: "Global Teams", value: "4", suffix: "" },
] as const;
